---
- name: Ensure ufw is installed
  ansible.builtin.package:
    name: ufw
    state: present

- name: Set UFW Rules
  community.general.ufw:
    rule: "{{ item.rule | default (omit) }}"
    port: "{{ item.port | default (omit) }}"
    proto: "{{ item.proto | default (omit) }}"
    comment: "{{ item.comment | default (omit) }}"
    interface: "{{ item.interface | default (omit) }}"
    direction: "{{ item.direction | default (omit) }}"
    route: "{{ item.route | default (omit) }}"
  loop: "{{ ufw_firewall_rules }}"
  notify: Reload UFW
